[Interface]
Address = 10.255.0.1/24
ListenPort = 51820
PrivateKey = 2Du8QF7qBaTa//zHv+ng5R+C/ePknghnXCeGCHtgPlM=
SaveConfig = true

# Add Peer sections below for clients (example):
#[Peer]
#PublicKey = <CLIENT_PUBKEY>
#AllowedIPs = 10.255.0.2/32
#PersistentKeepalive = 25
